---
title: "Strings and factors"
output: github_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
library(rvest)
library(p8105.datasets)
```

## Strings and manipulations

```{r}
string_vec = c("my", "name", "is", "Yingting")

str_detect(string_vec, "Yingting")
str_detect(string_vec, "i")
str_detect(string_vec, "YING")

str_replace(string_vec, "Yingting", "YINGTING Zhang")

#str_detect would shows in the vector, return the logic of the specific thing you mention. for example, there are 4 values including my, name, is, Yingting, when i mention str_dectect as Yingting, this would show F,F,F,T, as the first three dont show Yingting

```


```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")
str_detect(string_vec, "^i think")
#^: i think at beginning
str_detect(string_vec, "i think$")
#$: i think in the end
```


```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec, "Pumpkin")
str_detect(string_vec, "[Pp]umpkin")
#both upcase and lowcase p
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "[0-9]")
#anything between 0 and 9
str_detect(string_vec, "^[0-9]")
str_detect(string_vec, "^[0-9][a-z]")
#also same as a-z
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11")
#dot is a regular expression that match anything, as there are expression between 7 and 11, dot shows any expression with 7 and 11. however, since there is no expression at the third 711, this returns false

str_detect(string_vec, "7\\.11")
#two slashes "\\" mention the actual dot
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[[0-9]")
```


## Factors

```{r}
vec_sex = factor(c("male", "male", "female", "female"))
vec_sex
#comparing to string, this would show the level

as.numeric(vec_sex)

#what happens if i relevel...
vec_sex = fct_relevel(vec_sex, "male")
vec_sex
#make male as first level and female becomes second level, to relevel

as.numeric(vec_sex)

```

## NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj = 
  read_html(nsduh_url) |> 
  html_table() |> 
  first() |> 
  slice(-1)
```

need to tidy this!

```{r}
marj_df =
  table_marj |> 
  select(-contains("P Value")) |> # remove the columns that dont want
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent" 
  ) |> 
  separate(age_year, into = c("age", "year"), sep = "\\(") |> 
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-b]$", ""),
    percent = as.numeric(percent)) |> 
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))

#1. for the pivot section until the "values_to' this: pivot everything that isnt in the State column (want everything that isn State needs to be converted from wide to long, rename "age_year" with values; before that, this shows State with ordered and only State, age_year, and percent these three columns)

#2. separate the variable age_year, notice that we need to take more specific about what to separate sep = 

#3. use mutate to update the year variable, the way to do that is to find the pattern "\\)" and replace it with nothing----using str_replace

# continue the mutate function, about percent variable, we know that we want to skip a,b,c after the numbers, so we use str_replace function to find [a-c], and we know that they occurs at the end, so we can add $, and if find, replace nothing

#4. filter function shows that we dont want State variable to be one of either total_us, northest, midwest, south, west
```

## NSDUH --- factors
```{r}
marj_df |> 
  filter(age == "18-25") |> 
  mutate(State = fct_reorder(State, percent)) |> 
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

#fct_reorder: need to tell what variable need to reorder, this function would take the median value of the same category from different year (for example, Alabama in 2013, and 2014, there are different percent, in this case, this would show the midian of them)
```



## NYC Restaurant Inspections

```{r}
data("rest_inspec")

rest_inspec
```


```{r}
rest_inspec |> 
  count(boro, grade) |> 
  pivot_wider(
    names_from = grade,
    values_from = n
  ) |> 
  knitr::kable()
```

```{r}
inspection_df = 
  rest_inspec |> 
  filter(grade %in% c("A", "B", "C"), boro != "Missing") |> 
  mutate(
    boro = str_to_title(boro),
    dba = str_to_upper(dba))
```

Pizza places

```{r}
inspection_df |> 
  filter(str_detect(dba, "PIZZA")) |> 
  count(boro)
```


```{r}
inspection_df |> 
  filter(str_detect(dba, "PIZZA")) |> 
  mutate(boro = fct_infreq(boro)) |> 
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar()
```




```{r}
inspection_df |> 
  filter(str_detect(dba, "PIZZA")) |> 
  mutate(
    boro = fct_infreq(boro), 
    boro = str_replace(boro, "Manhattan", "The City")) |> 
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar()
```

```{r}
inspection_df |> 
  filter(str_detect(dba, "PIZZA")) |> 
  mutate(
    boro = fct_infreq(boro), 
    boro = fct_recode(boro, "The City" = "Manhattan")) |> 
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar()
```







